server:
    log_level: info

metrics:
    wal_directory: /tmp/agent-wal
    global:
      scrape_interval: 15s
    configs:
      - name: render
        scrape_configs:
          - job_name: api-service
            scheme: https
            # Override API_METRICS_PATH if your endpoint is not /metrics.
            metrics_path: ${API_METRICS_PATH:-/metrics}
            static_configs:
              # API_TARGET_HOST should be host (and optional port) only, no path.
              - targets: ['${API_TARGET_HOST}']
        remote_write:
          - url: ${PROM_REMOTE_WRITE_URL}
            basic_auth:
              username: ${PROM_REMOTE_WRITE_USER}
              password: ${PROM_REMOTE_WRITE_PASS}
