# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import analysis_pb2 as analysis__pb2


class AnalysisServiceStub(object):
    """Analysis Service - Handles code analysis requests
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeCode = channel.unary_unary(
                '/analysis.AnalysisService/AnalyzeCode',
                request_serializer=analysis__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=analysis__pb2.AnalysisResponse.FromString,
                )
        self.GetAnalysis = channel.unary_unary(
                '/analysis.AnalysisService/GetAnalysis',
                request_serializer=analysis__pb2.GetAnalysisRequest.SerializeToString,
                response_deserializer=analysis__pb2.AnalysisResponse.FromString,
                )
        self.BatchAnalyze = channel.unary_unary(
                '/analysis.AnalysisService/BatchAnalyze',
                request_serializer=analysis__pb2.BatchAnalyzeRequest.SerializeToString,
                response_deserializer=analysis__pb2.BatchAnalysisResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/analysis.AnalysisService/HealthCheck',
                request_serializer=analysis__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=analysis__pb2.HealthCheckResponse.FromString,
                )


class AnalysisServiceServicer(object):
    """Analysis Service - Handles code analysis requests
    """

    def AnalyzeCode(self, request, context):
        """Analyze code from a pull request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalysis(self, request, context):
        """Get analysis result by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchAnalyze(self, request, context):
        """Batch analyze multiple files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCode,
                    request_deserializer=analysis__pb2.AnalyzeRequest.FromString,
                    response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
            ),
            'GetAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysis,
                    request_deserializer=analysis__pb2.GetAnalysisRequest.FromString,
                    response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
            ),
            'BatchAnalyze': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchAnalyze,
                    request_deserializer=analysis__pb2.BatchAnalyzeRequest.FromString,
                    response_serializer=analysis__pb2.BatchAnalysisResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=analysis__pb2.HealthCheckRequest.FromString,
                    response_serializer=analysis__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analysis.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """Analysis Service - Handles code analysis requests
    """

    @staticmethod
    def AnalyzeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analysis.AnalysisService/AnalyzeCode',
            analysis__pb2.AnalyzeRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analysis.AnalysisService/GetAnalysis',
            analysis__pb2.GetAnalysisRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchAnalyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analysis.AnalysisService/BatchAnalyze',
            analysis__pb2.BatchAnalyzeRequest.SerializeToString,
            analysis__pb2.BatchAnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analysis.AnalysisService/HealthCheck',
            analysis__pb2.HealthCheckRequest.SerializeToString,
            analysis__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
