# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import github_pb2 as github__pb2


class GitHubServiceStub(object):
    """GitHub Service - Handles GitHub operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPullRequest = channel.unary_unary(
                '/github.GitHubService/GetPullRequest',
                request_serializer=github__pb2.GetPRRequest.SerializeToString,
                response_deserializer=github__pb2.PullRequestResponse.FromString,
                )
        self.PostComment = channel.unary_unary(
                '/github.GitHubService/PostComment',
                request_serializer=github__pb2.PostCommentRequest.SerializeToString,
                response_deserializer=github__pb2.CommentResponse.FromString,
                )
        self.UpdateStatus = channel.unary_unary(
                '/github.GitHubService/UpdateStatus',
                request_serializer=github__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=github__pb2.StatusResponse.FromString,
                )
        self.GetRepositoryFiles = channel.unary_unary(
                '/github.GitHubService/GetRepositoryFiles',
                request_serializer=github__pb2.GetFilesRequest.SerializeToString,
                response_deserializer=github__pb2.FilesResponse.FromString,
                )
        self.ProcessWebhook = channel.unary_unary(
                '/github.GitHubService/ProcessWebhook',
                request_serializer=github__pb2.WebhookRequest.SerializeToString,
                response_deserializer=github__pb2.WebhookResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/github.GitHubService/HealthCheck',
                request_serializer=github__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=github__pb2.HealthCheckResponse.FromString,
                )


class GitHubServiceServicer(object):
    """GitHub Service - Handles GitHub operations
    """

    def GetPullRequest(self, request, context):
        """Get pull request details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostComment(self, request, context):
        """Post analysis comment to PR
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Update PR status check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRepositoryFiles(self, request, context):
        """Get repository files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessWebhook(self, request, context):
        """Process webhook event
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitHubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPullRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPullRequest,
                    request_deserializer=github__pb2.GetPRRequest.FromString,
                    response_serializer=github__pb2.PullRequestResponse.SerializeToString,
            ),
            'PostComment': grpc.unary_unary_rpc_method_handler(
                    servicer.PostComment,
                    request_deserializer=github__pb2.PostCommentRequest.FromString,
                    response_serializer=github__pb2.CommentResponse.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=github__pb2.UpdateStatusRequest.FromString,
                    response_serializer=github__pb2.StatusResponse.SerializeToString,
            ),
            'GetRepositoryFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepositoryFiles,
                    request_deserializer=github__pb2.GetFilesRequest.FromString,
                    response_serializer=github__pb2.FilesResponse.SerializeToString,
            ),
            'ProcessWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessWebhook,
                    request_deserializer=github__pb2.WebhookRequest.FromString,
                    response_serializer=github__pb2.WebhookResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=github__pb2.HealthCheckRequest.FromString,
                    response_serializer=github__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'github.GitHubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GitHubService(object):
    """GitHub Service - Handles GitHub operations
    """

    @staticmethod
    def GetPullRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/github.GitHubService/GetPullRequest',
            github__pb2.GetPRRequest.SerializeToString,
            github__pb2.PullRequestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/github.GitHubService/PostComment',
            github__pb2.PostCommentRequest.SerializeToString,
            github__pb2.CommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/github.GitHubService/UpdateStatus',
            github__pb2.UpdateStatusRequest.SerializeToString,
            github__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRepositoryFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/github.GitHubService/GetRepositoryFiles',
            github__pb2.GetFilesRequest.SerializeToString,
            github__pb2.FilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/github.GitHubService/ProcessWebhook',
            github__pb2.WebhookRequest.SerializeToString,
            github__pb2.WebhookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/github.GitHubService/HealthCheck',
            github__pb2.HealthCheckRequest.SerializeToString,
            github__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
