// source: analysis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.analysis.AnalysisConfig', null, global);
goog.exportSymbol('proto.analysis.AnalysisResponse', null, global);
goog.exportSymbol('proto.analysis.AnalysisResult', null, global);
goog.exportSymbol('proto.analysis.AnalyzeRequest', null, global);
goog.exportSymbol('proto.analysis.BatchAnalysisResponse', null, global);
goog.exportSymbol('proto.analysis.BatchAnalyzeRequest', null, global);
goog.exportSymbol('proto.analysis.CodeFile', null, global);
goog.exportSymbol('proto.analysis.GetAnalysisRequest', null, global);
goog.exportSymbol('proto.analysis.HealthCheckRequest', null, global);
goog.exportSymbol('proto.analysis.HealthCheckResponse', null, global);
goog.exportSymbol('proto.analysis.Issue', null, global);
goog.exportSymbol('proto.analysis.Metrics', null, global);
goog.exportSymbol('proto.analysis.Summary', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.AnalyzeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.analysis.AnalyzeRequest.repeatedFields_, null);
};
goog.inherits(proto.analysis.AnalyzeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.AnalyzeRequest.displayName = 'proto.analysis.AnalyzeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.CodeFile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.analysis.CodeFile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.CodeFile.displayName = 'proto.analysis.CodeFile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.AnalysisConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.analysis.AnalysisConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.AnalysisConfig.displayName = 'proto.analysis.AnalysisConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.AnalysisResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.analysis.AnalysisResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.AnalysisResponse.displayName = 'proto.analysis.AnalysisResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.AnalysisResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.analysis.AnalysisResult.repeatedFields_, null);
};
goog.inherits(proto.analysis.AnalysisResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.AnalysisResult.displayName = 'proto.analysis.AnalysisResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.Issue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.analysis.Issue.repeatedFields_, null);
};
goog.inherits(proto.analysis.Issue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.Issue.displayName = 'proto.analysis.Issue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.Summary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.analysis.Summary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.Summary.displayName = 'proto.analysis.Summary';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.Metrics = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.analysis.Metrics, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.Metrics.displayName = 'proto.analysis.Metrics';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.GetAnalysisRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.analysis.GetAnalysisRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.GetAnalysisRequest.displayName = 'proto.analysis.GetAnalysisRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.BatchAnalyzeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.analysis.BatchAnalyzeRequest.repeatedFields_, null);
};
goog.inherits(proto.analysis.BatchAnalyzeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.BatchAnalyzeRequest.displayName = 'proto.analysis.BatchAnalyzeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.BatchAnalysisResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.analysis.BatchAnalysisResponse.repeatedFields_, null);
};
goog.inherits(proto.analysis.BatchAnalysisResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.BatchAnalysisResponse.displayName = 'proto.analysis.BatchAnalysisResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.HealthCheckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.analysis.HealthCheckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.HealthCheckRequest.displayName = 'proto.analysis.HealthCheckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.analysis.HealthCheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.analysis.HealthCheckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.analysis.HealthCheckResponse.displayName = 'proto.analysis.HealthCheckResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.analysis.AnalyzeRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.AnalyzeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.AnalyzeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.AnalyzeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.AnalyzeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pullRequestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    repositoryId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    filesList: jspb.Message.toObjectList(msg.getFilesList(),
    proto.analysis.CodeFile.toObject, includeInstance),
    config: (f = msg.getConfig()) && proto.analysis.AnalysisConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.AnalyzeRequest}
 */
proto.analysis.AnalyzeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.AnalyzeRequest;
  return proto.analysis.AnalyzeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.AnalyzeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.AnalyzeRequest}
 */
proto.analysis.AnalyzeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPullRequestId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepositoryId(value);
      break;
    case 3:
      var value = new proto.analysis.CodeFile;
      reader.readMessage(value,proto.analysis.CodeFile.deserializeBinaryFromReader);
      msg.addFiles(value);
      break;
    case 4:
      var value = new proto.analysis.AnalysisConfig;
      reader.readMessage(value,proto.analysis.AnalysisConfig.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.AnalyzeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.AnalyzeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.AnalyzeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.AnalyzeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPullRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRepositoryId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFilesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.analysis.CodeFile.serializeBinaryToWriter
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.analysis.AnalysisConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional string pull_request_id = 1;
 * @return {string}
 */
proto.analysis.AnalyzeRequest.prototype.getPullRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.AnalyzeRequest} returns this
 */
proto.analysis.AnalyzeRequest.prototype.setPullRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string repository_id = 2;
 * @return {string}
 */
proto.analysis.AnalyzeRequest.prototype.getRepositoryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.AnalyzeRequest} returns this
 */
proto.analysis.AnalyzeRequest.prototype.setRepositoryId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated CodeFile files = 3;
 * @return {!Array<!proto.analysis.CodeFile>}
 */
proto.analysis.AnalyzeRequest.prototype.getFilesList = function() {
  return /** @type{!Array<!proto.analysis.CodeFile>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.analysis.CodeFile, 3));
};


/**
 * @param {!Array<!proto.analysis.CodeFile>} value
 * @return {!proto.analysis.AnalyzeRequest} returns this
*/
proto.analysis.AnalyzeRequest.prototype.setFilesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.analysis.CodeFile=} opt_value
 * @param {number=} opt_index
 * @return {!proto.analysis.CodeFile}
 */
proto.analysis.AnalyzeRequest.prototype.addFiles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.analysis.CodeFile, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.analysis.AnalyzeRequest} returns this
 */
proto.analysis.AnalyzeRequest.prototype.clearFilesList = function() {
  return this.setFilesList([]);
};


/**
 * optional AnalysisConfig config = 4;
 * @return {?proto.analysis.AnalysisConfig}
 */
proto.analysis.AnalyzeRequest.prototype.getConfig = function() {
  return /** @type{?proto.analysis.AnalysisConfig} */ (
    jspb.Message.getWrapperField(this, proto.analysis.AnalysisConfig, 4));
};


/**
 * @param {?proto.analysis.AnalysisConfig|undefined} value
 * @return {!proto.analysis.AnalyzeRequest} returns this
*/
proto.analysis.AnalyzeRequest.prototype.setConfig = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.analysis.AnalyzeRequest} returns this
 */
proto.analysis.AnalyzeRequest.prototype.clearConfig = function() {
  return this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.analysis.AnalyzeRequest.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.CodeFile.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.CodeFile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.CodeFile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.CodeFile.toObject = function(includeInstance, msg) {
  var f, obj = {
    filename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    content: jspb.Message.getFieldWithDefault(msg, 2, ""),
    language: jspb.Message.getFieldWithDefault(msg, 3, ""),
    linesOfCode: jspb.Message.getFieldWithDefault(msg, 4, 0),
    filePath: jspb.Message.getFieldWithDefault(msg, 5, ""),
    changeType: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.CodeFile}
 */
proto.analysis.CodeFile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.CodeFile;
  return proto.analysis.CodeFile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.CodeFile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.CodeFile}
 */
proto.analysis.CodeFile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLinesOfCode(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilePath(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setChangeType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.CodeFile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.CodeFile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.CodeFile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.CodeFile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLinesOfCode();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getFilePath();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getChangeType();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string filename = 1;
 * @return {string}
 */
proto.analysis.CodeFile.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.CodeFile} returns this
 */
proto.analysis.CodeFile.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string content = 2;
 * @return {string}
 */
proto.analysis.CodeFile.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.CodeFile} returns this
 */
proto.analysis.CodeFile.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string language = 3;
 * @return {string}
 */
proto.analysis.CodeFile.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.CodeFile} returns this
 */
proto.analysis.CodeFile.prototype.setLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 lines_of_code = 4;
 * @return {number}
 */
proto.analysis.CodeFile.prototype.getLinesOfCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.CodeFile} returns this
 */
proto.analysis.CodeFile.prototype.setLinesOfCode = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string file_path = 5;
 * @return {string}
 */
proto.analysis.CodeFile.prototype.getFilePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.CodeFile} returns this
 */
proto.analysis.CodeFile.prototype.setFilePath = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string change_type = 6;
 * @return {string}
 */
proto.analysis.CodeFile.prototype.getChangeType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.CodeFile} returns this
 */
proto.analysis.CodeFile.prototype.setChangeType = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.AnalysisConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.AnalysisConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.AnalysisConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.AnalysisConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    enableSecurityScan: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    enablePerformanceScan: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    enableStyleCheck: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    enableBestPractices: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    severityThreshold: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.AnalysisConfig}
 */
proto.analysis.AnalysisConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.AnalysisConfig;
  return proto.analysis.AnalysisConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.AnalysisConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.AnalysisConfig}
 */
proto.analysis.AnalysisConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableSecurityScan(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnablePerformanceScan(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableStyleCheck(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableBestPractices(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSeverityThreshold(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.AnalysisConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.AnalysisConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.AnalysisConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.AnalysisConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnableSecurityScan();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getEnablePerformanceScan();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getEnableStyleCheck();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getEnableBestPractices();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getSeverityThreshold();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional bool enable_security_scan = 1;
 * @return {boolean}
 */
proto.analysis.AnalysisConfig.prototype.getEnableSecurityScan = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.analysis.AnalysisConfig} returns this
 */
proto.analysis.AnalysisConfig.prototype.setEnableSecurityScan = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool enable_performance_scan = 2;
 * @return {boolean}
 */
proto.analysis.AnalysisConfig.prototype.getEnablePerformanceScan = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.analysis.AnalysisConfig} returns this
 */
proto.analysis.AnalysisConfig.prototype.setEnablePerformanceScan = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool enable_style_check = 3;
 * @return {boolean}
 */
proto.analysis.AnalysisConfig.prototype.getEnableStyleCheck = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.analysis.AnalysisConfig} returns this
 */
proto.analysis.AnalysisConfig.prototype.setEnableStyleCheck = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool enable_best_practices = 4;
 * @return {boolean}
 */
proto.analysis.AnalysisConfig.prototype.getEnableBestPractices = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.analysis.AnalysisConfig} returns this
 */
proto.analysis.AnalysisConfig.prototype.setEnableBestPractices = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string severity_threshold = 5;
 * @return {string}
 */
proto.analysis.AnalysisConfig.prototype.getSeverityThreshold = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.AnalysisConfig} returns this
 */
proto.analysis.AnalysisConfig.prototype.setSeverityThreshold = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.AnalysisResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.AnalysisResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.AnalysisResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.AnalysisResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    analysisId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: jspb.Message.getFieldWithDefault(msg, 2, ""),
    result: (f = msg.getResult()) && proto.analysis.AnalysisResult.toObject(includeInstance, f),
    errorMessage: jspb.Message.getFieldWithDefault(msg, 4, ""),
    createdAt: jspb.Message.getFieldWithDefault(msg, 5, 0),
    completedAt: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.AnalysisResponse}
 */
proto.analysis.AnalysisResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.AnalysisResponse;
  return proto.analysis.AnalysisResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.AnalysisResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.AnalysisResponse}
 */
proto.analysis.AnalysisResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnalysisId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 3:
      var value = new proto.analysis.AnalysisResult;
      reader.readMessage(value,proto.analysis.AnalysisResult.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedAt(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCompletedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.AnalysisResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.AnalysisResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.AnalysisResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.AnalysisResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnalysisId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.analysis.AnalysisResult.serializeBinaryToWriter
    );
  }
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCreatedAt();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getCompletedAt();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
};


/**
 * optional string analysis_id = 1;
 * @return {string}
 */
proto.analysis.AnalysisResponse.prototype.getAnalysisId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.AnalysisResponse} returns this
 */
proto.analysis.AnalysisResponse.prototype.setAnalysisId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string status = 2;
 * @return {string}
 */
proto.analysis.AnalysisResponse.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.AnalysisResponse} returns this
 */
proto.analysis.AnalysisResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional AnalysisResult result = 3;
 * @return {?proto.analysis.AnalysisResult}
 */
proto.analysis.AnalysisResponse.prototype.getResult = function() {
  return /** @type{?proto.analysis.AnalysisResult} */ (
    jspb.Message.getWrapperField(this, proto.analysis.AnalysisResult, 3));
};


/**
 * @param {?proto.analysis.AnalysisResult|undefined} value
 * @return {!proto.analysis.AnalysisResponse} returns this
*/
proto.analysis.AnalysisResponse.prototype.setResult = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.analysis.AnalysisResponse} returns this
 */
proto.analysis.AnalysisResponse.prototype.clearResult = function() {
  return this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.analysis.AnalysisResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string error_message = 4;
 * @return {string}
 */
proto.analysis.AnalysisResponse.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.AnalysisResponse} returns this
 */
proto.analysis.AnalysisResponse.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 created_at = 5;
 * @return {number}
 */
proto.analysis.AnalysisResponse.prototype.getCreatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.AnalysisResponse} returns this
 */
proto.analysis.AnalysisResponse.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 completed_at = 6;
 * @return {number}
 */
proto.analysis.AnalysisResponse.prototype.getCompletedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.AnalysisResponse} returns this
 */
proto.analysis.AnalysisResponse.prototype.setCompletedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.analysis.AnalysisResult.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.AnalysisResult.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.AnalysisResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.AnalysisResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.AnalysisResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuesList: jspb.Message.toObjectList(msg.getIssuesList(),
    proto.analysis.Issue.toObject, includeInstance),
    summary: (f = msg.getSummary()) && proto.analysis.Summary.toObject(includeInstance, f),
    metrics: (f = msg.getMetrics()) && proto.analysis.Metrics.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.AnalysisResult}
 */
proto.analysis.AnalysisResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.AnalysisResult;
  return proto.analysis.AnalysisResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.AnalysisResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.AnalysisResult}
 */
proto.analysis.AnalysisResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.analysis.Issue;
      reader.readMessage(value,proto.analysis.Issue.deserializeBinaryFromReader);
      msg.addIssues(value);
      break;
    case 2:
      var value = new proto.analysis.Summary;
      reader.readMessage(value,proto.analysis.Summary.deserializeBinaryFromReader);
      msg.setSummary(value);
      break;
    case 3:
      var value = new proto.analysis.Metrics;
      reader.readMessage(value,proto.analysis.Metrics.deserializeBinaryFromReader);
      msg.setMetrics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.AnalysisResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.AnalysisResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.AnalysisResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.AnalysisResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.analysis.Issue.serializeBinaryToWriter
    );
  }
  f = message.getSummary();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.analysis.Summary.serializeBinaryToWriter
    );
  }
  f = message.getMetrics();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.analysis.Metrics.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Issue issues = 1;
 * @return {!Array<!proto.analysis.Issue>}
 */
proto.analysis.AnalysisResult.prototype.getIssuesList = function() {
  return /** @type{!Array<!proto.analysis.Issue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.analysis.Issue, 1));
};


/**
 * @param {!Array<!proto.analysis.Issue>} value
 * @return {!proto.analysis.AnalysisResult} returns this
*/
proto.analysis.AnalysisResult.prototype.setIssuesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.analysis.Issue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.analysis.Issue}
 */
proto.analysis.AnalysisResult.prototype.addIssues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.analysis.Issue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.analysis.AnalysisResult} returns this
 */
proto.analysis.AnalysisResult.prototype.clearIssuesList = function() {
  return this.setIssuesList([]);
};


/**
 * optional Summary summary = 2;
 * @return {?proto.analysis.Summary}
 */
proto.analysis.AnalysisResult.prototype.getSummary = function() {
  return /** @type{?proto.analysis.Summary} */ (
    jspb.Message.getWrapperField(this, proto.analysis.Summary, 2));
};


/**
 * @param {?proto.analysis.Summary|undefined} value
 * @return {!proto.analysis.AnalysisResult} returns this
*/
proto.analysis.AnalysisResult.prototype.setSummary = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.analysis.AnalysisResult} returns this
 */
proto.analysis.AnalysisResult.prototype.clearSummary = function() {
  return this.setSummary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.analysis.AnalysisResult.prototype.hasSummary = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Metrics metrics = 3;
 * @return {?proto.analysis.Metrics}
 */
proto.analysis.AnalysisResult.prototype.getMetrics = function() {
  return /** @type{?proto.analysis.Metrics} */ (
    jspb.Message.getWrapperField(this, proto.analysis.Metrics, 3));
};


/**
 * @param {?proto.analysis.Metrics|undefined} value
 * @return {!proto.analysis.AnalysisResult} returns this
*/
proto.analysis.AnalysisResult.prototype.setMetrics = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.analysis.AnalysisResult} returns this
 */
proto.analysis.AnalysisResult.prototype.clearMetrics = function() {
  return this.setMetrics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.analysis.AnalysisResult.prototype.hasMetrics = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.analysis.Issue.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.Issue.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.Issue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.Issue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.Issue.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, ""),
    severity: jspb.Message.getFieldWithDefault(msg, 3, ""),
    title: jspb.Message.getFieldWithDefault(msg, 4, ""),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    file: jspb.Message.getFieldWithDefault(msg, 6, ""),
    lineStart: jspb.Message.getFieldWithDefault(msg, 7, 0),
    lineEnd: jspb.Message.getFieldWithDefault(msg, 8, 0),
    codeSnippet: jspb.Message.getFieldWithDefault(msg, 9, ""),
    suggestion: jspb.Message.getFieldWithDefault(msg, 10, ""),
    referencesList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.Issue}
 */
proto.analysis.Issue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.Issue;
  return proto.analysis.Issue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.Issue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.Issue}
 */
proto.analysis.Issue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSeverity(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFile(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLineStart(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLineEnd(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodeSnippet(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSuggestion(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addReferences(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.Issue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.Issue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.Issue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.Issue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSeverity();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getFile();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLineStart();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getLineEnd();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getCodeSnippet();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getSuggestion();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getReferencesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.analysis.Issue.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.analysis.Issue.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string severity = 3;
 * @return {string}
 */
proto.analysis.Issue.prototype.getSeverity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setSeverity = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string title = 4;
 * @return {string}
 */
proto.analysis.Issue.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.analysis.Issue.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string file = 6;
 * @return {string}
 */
proto.analysis.Issue.prototype.getFile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setFile = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 line_start = 7;
 * @return {number}
 */
proto.analysis.Issue.prototype.getLineStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setLineStart = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 line_end = 8;
 * @return {number}
 */
proto.analysis.Issue.prototype.getLineEnd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setLineEnd = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string code_snippet = 9;
 * @return {string}
 */
proto.analysis.Issue.prototype.getCodeSnippet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setCodeSnippet = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string suggestion = 10;
 * @return {string}
 */
proto.analysis.Issue.prototype.getSuggestion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setSuggestion = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * repeated string references = 11;
 * @return {!Array<string>}
 */
proto.analysis.Issue.prototype.getReferencesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.setReferencesList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.addReferences = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.analysis.Issue} returns this
 */
proto.analysis.Issue.prototype.clearReferencesList = function() {
  return this.setReferencesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.Summary.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.Summary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.Summary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.Summary.toObject = function(includeInstance, msg) {
  var f, obj = {
    totalIssues: jspb.Message.getFieldWithDefault(msg, 1, 0),
    criticalIssues: jspb.Message.getFieldWithDefault(msg, 2, 0),
    highIssues: jspb.Message.getFieldWithDefault(msg, 3, 0),
    mediumIssues: jspb.Message.getFieldWithDefault(msg, 4, 0),
    lowIssues: jspb.Message.getFieldWithDefault(msg, 5, 0),
    filesAnalyzed: jspb.Message.getFieldWithDefault(msg, 6, 0),
    overallQuality: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.Summary}
 */
proto.analysis.Summary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.Summary;
  return proto.analysis.Summary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.Summary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.Summary}
 */
proto.analysis.Summary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalIssues(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCriticalIssues(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHighIssues(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMediumIssues(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLowIssues(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFilesAnalyzed(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setOverallQuality(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.Summary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.Summary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.Summary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.Summary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTotalIssues();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCriticalIssues();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getHighIssues();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getMediumIssues();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLowIssues();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getFilesAnalyzed();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getOverallQuality();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional int32 total_issues = 1;
 * @return {number}
 */
proto.analysis.Summary.prototype.getTotalIssues = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Summary} returns this
 */
proto.analysis.Summary.prototype.setTotalIssues = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 critical_issues = 2;
 * @return {number}
 */
proto.analysis.Summary.prototype.getCriticalIssues = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Summary} returns this
 */
proto.analysis.Summary.prototype.setCriticalIssues = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 high_issues = 3;
 * @return {number}
 */
proto.analysis.Summary.prototype.getHighIssues = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Summary} returns this
 */
proto.analysis.Summary.prototype.setHighIssues = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 medium_issues = 4;
 * @return {number}
 */
proto.analysis.Summary.prototype.getMediumIssues = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Summary} returns this
 */
proto.analysis.Summary.prototype.setMediumIssues = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 low_issues = 5;
 * @return {number}
 */
proto.analysis.Summary.prototype.getLowIssues = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Summary} returns this
 */
proto.analysis.Summary.prototype.setLowIssues = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 files_analyzed = 6;
 * @return {number}
 */
proto.analysis.Summary.prototype.getFilesAnalyzed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Summary} returns this
 */
proto.analysis.Summary.prototype.setFilesAnalyzed = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string overall_quality = 7;
 * @return {string}
 */
proto.analysis.Summary.prototype.getOverallQuality = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.Summary} returns this
 */
proto.analysis.Summary.prototype.setOverallQuality = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.Metrics.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.Metrics.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.Metrics} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.Metrics.toObject = function(includeInstance, msg) {
  var f, obj = {
    linesAnalyzed: jspb.Message.getFieldWithDefault(msg, 1, 0),
    complexityScore: jspb.Message.getFieldWithDefault(msg, 2, 0),
    maintainabilityIndex: jspb.Message.getFieldWithDefault(msg, 3, 0),
    processingTimeMs: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.Metrics}
 */
proto.analysis.Metrics.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.Metrics;
  return proto.analysis.Metrics.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.Metrics} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.Metrics}
 */
proto.analysis.Metrics.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLinesAnalyzed(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setComplexityScore(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaintainabilityIndex(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setProcessingTimeMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.Metrics.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.Metrics.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.Metrics} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.Metrics.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLinesAnalyzed();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getComplexityScore();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMaintainabilityIndex();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getProcessingTimeMs();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * optional int32 lines_analyzed = 1;
 * @return {number}
 */
proto.analysis.Metrics.prototype.getLinesAnalyzed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Metrics} returns this
 */
proto.analysis.Metrics.prototype.setLinesAnalyzed = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 complexity_score = 2;
 * @return {number}
 */
proto.analysis.Metrics.prototype.getComplexityScore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Metrics} returns this
 */
proto.analysis.Metrics.prototype.setComplexityScore = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 maintainability_index = 3;
 * @return {number}
 */
proto.analysis.Metrics.prototype.getMaintainabilityIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Metrics} returns this
 */
proto.analysis.Metrics.prototype.setMaintainabilityIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional double processing_time_ms = 4;
 * @return {number}
 */
proto.analysis.Metrics.prototype.getProcessingTimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.Metrics} returns this
 */
proto.analysis.Metrics.prototype.setProcessingTimeMs = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.GetAnalysisRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.GetAnalysisRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.GetAnalysisRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.GetAnalysisRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    analysisId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.GetAnalysisRequest}
 */
proto.analysis.GetAnalysisRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.GetAnalysisRequest;
  return proto.analysis.GetAnalysisRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.GetAnalysisRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.GetAnalysisRequest}
 */
proto.analysis.GetAnalysisRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnalysisId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.GetAnalysisRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.GetAnalysisRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.GetAnalysisRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.GetAnalysisRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnalysisId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string analysis_id = 1;
 * @return {string}
 */
proto.analysis.GetAnalysisRequest.prototype.getAnalysisId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.GetAnalysisRequest} returns this
 */
proto.analysis.GetAnalysisRequest.prototype.setAnalysisId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.analysis.BatchAnalyzeRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.BatchAnalyzeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.BatchAnalyzeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.BatchAnalyzeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.BatchAnalyzeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestsList: jspb.Message.toObjectList(msg.getRequestsList(),
    proto.analysis.AnalyzeRequest.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.BatchAnalyzeRequest}
 */
proto.analysis.BatchAnalyzeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.BatchAnalyzeRequest;
  return proto.analysis.BatchAnalyzeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.BatchAnalyzeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.BatchAnalyzeRequest}
 */
proto.analysis.BatchAnalyzeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.analysis.AnalyzeRequest;
      reader.readMessage(value,proto.analysis.AnalyzeRequest.deserializeBinaryFromReader);
      msg.addRequests(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.BatchAnalyzeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.BatchAnalyzeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.BatchAnalyzeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.BatchAnalyzeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.analysis.AnalyzeRequest.serializeBinaryToWriter
    );
  }
};


/**
 * repeated AnalyzeRequest requests = 1;
 * @return {!Array<!proto.analysis.AnalyzeRequest>}
 */
proto.analysis.BatchAnalyzeRequest.prototype.getRequestsList = function() {
  return /** @type{!Array<!proto.analysis.AnalyzeRequest>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.analysis.AnalyzeRequest, 1));
};


/**
 * @param {!Array<!proto.analysis.AnalyzeRequest>} value
 * @return {!proto.analysis.BatchAnalyzeRequest} returns this
*/
proto.analysis.BatchAnalyzeRequest.prototype.setRequestsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.analysis.AnalyzeRequest=} opt_value
 * @param {number=} opt_index
 * @return {!proto.analysis.AnalyzeRequest}
 */
proto.analysis.BatchAnalyzeRequest.prototype.addRequests = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.analysis.AnalyzeRequest, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.analysis.BatchAnalyzeRequest} returns this
 */
proto.analysis.BatchAnalyzeRequest.prototype.clearRequestsList = function() {
  return this.setRequestsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.analysis.BatchAnalysisResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.BatchAnalysisResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.BatchAnalysisResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.BatchAnalysisResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.BatchAnalysisResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    responsesList: jspb.Message.toObjectList(msg.getResponsesList(),
    proto.analysis.AnalysisResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.BatchAnalysisResponse}
 */
proto.analysis.BatchAnalysisResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.BatchAnalysisResponse;
  return proto.analysis.BatchAnalysisResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.BatchAnalysisResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.BatchAnalysisResponse}
 */
proto.analysis.BatchAnalysisResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.analysis.AnalysisResponse;
      reader.readMessage(value,proto.analysis.AnalysisResponse.deserializeBinaryFromReader);
      msg.addResponses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.BatchAnalysisResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.BatchAnalysisResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.BatchAnalysisResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.BatchAnalysisResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponsesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.analysis.AnalysisResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated AnalysisResponse responses = 1;
 * @return {!Array<!proto.analysis.AnalysisResponse>}
 */
proto.analysis.BatchAnalysisResponse.prototype.getResponsesList = function() {
  return /** @type{!Array<!proto.analysis.AnalysisResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.analysis.AnalysisResponse, 1));
};


/**
 * @param {!Array<!proto.analysis.AnalysisResponse>} value
 * @return {!proto.analysis.BatchAnalysisResponse} returns this
*/
proto.analysis.BatchAnalysisResponse.prototype.setResponsesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.analysis.AnalysisResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.analysis.AnalysisResponse}
 */
proto.analysis.BatchAnalysisResponse.prototype.addResponses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.analysis.AnalysisResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.analysis.BatchAnalysisResponse} returns this
 */
proto.analysis.BatchAnalysisResponse.prototype.clearResponsesList = function() {
  return this.setResponsesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.HealthCheckRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.HealthCheckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.HealthCheckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.HealthCheckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.HealthCheckRequest}
 */
proto.analysis.HealthCheckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.HealthCheckRequest;
  return proto.analysis.HealthCheckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.HealthCheckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.HealthCheckRequest}
 */
proto.analysis.HealthCheckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.HealthCheckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.HealthCheckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.HealthCheckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.HealthCheckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.analysis.HealthCheckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.analysis.HealthCheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.analysis.HealthCheckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.HealthCheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, ""),
    uptimeSeconds: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.analysis.HealthCheckResponse}
 */
proto.analysis.HealthCheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.analysis.HealthCheckResponse;
  return proto.analysis.HealthCheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.analysis.HealthCheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.analysis.HealthCheckResponse}
 */
proto.analysis.HealthCheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUptimeSeconds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.analysis.HealthCheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.analysis.HealthCheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.analysis.HealthCheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.analysis.HealthCheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUptimeSeconds();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional string status = 1;
 * @return {string}
 */
proto.analysis.HealthCheckResponse.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.HealthCheckResponse} returns this
 */
proto.analysis.HealthCheckResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.analysis.HealthCheckResponse.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.analysis.HealthCheckResponse} returns this
 */
proto.analysis.HealthCheckResponse.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 uptime_seconds = 3;
 * @return {number}
 */
proto.analysis.HealthCheckResponse.prototype.getUptimeSeconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.analysis.HealthCheckResponse} returns this
 */
proto.analysis.HealthCheckResponse.prototype.setUptimeSeconds = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.analysis);
